{% set name = "pluginbase" %}
{% set version = "1.0.0" %}
{% set sha256 = "497894df38d0db71e1a4fbbfaceb10c3ef49a3f95a0582e11b75f8adaa030005" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pluginbase

about:
  home: http://github.com/mitsuhiko/pluginbase
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A support library for building plugins sytems in Python.
  dev_url: https://github.com/mitsuhiko/pluginbase

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/46418
    reason: Client request
  recipe-maintainers:
    - ianaobi
    - windelbouwman
    - abloemert
