travis:
  secure:
    BINSTAR_TOKEN: s5r6a8ruQjDIGU0wXO7Mv/Qp/5yU2ID83vln29eP86unIo2703qJVtwkXcaTuGINGq//FACv4oNc9/hxALlz6yWMyO707qF27RTPdkC6ByD9nx/sXSQj8bgTskFL2gjOcetSK7FQsb9wXbttmWPCzCS4G8UEmkDwJlGac3oOvXB0gkLFNUEmfjcsG+ST9JX6sxIVakyyyo2zxPruoq2+YMzuNHQA+KfefiUb15Bf9Uwe2eoK8w4CFclp6PS6fm5SkhXIkjRMauKUfwYEqaLQaxJ99lv70ec3lKs81wc1wCj0/6i1Nk5yi4PcyVtr1kZnqQalTsaK0mMA1pR2h+cHXTIURUBg4u+H9671xd+H2v/Audl8MlUzaTcEoM9YJPMqGT307uGiPk4nruOx8v8BV6o4tZO0aBemDkPzsk5YnSXtYg0W1qWAFvrK+dg9IKdIZDdv9Mrl+rObUr2tGhL0AGojmmxfF268tTdDEBGRUw3xy+HWF1GTOnhKlhHF2YLFrDR5+s3VNJYb6xjdFrmBCALMrZBldoFllaO+Zdm0hqh1WRI8yhisaDuluUrK3T9nHVXTBgqUx4Z5Q77p1Ig+lUxavJuH8qFc3wLdTAhtVQ/N03nFhZobjfn9r1f62RX5V5WvbWX0xYhV0QeOzQ1kS+sX76laBIEEQxUSIs2ymGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
