travis:
  secure:
    BINSTAR_TOKEN: P+kOyBkhZOcOnQpuFSUrPLE5bw+Pu0iWZKUDBZRorqjof+aipzcvyLuS5Pt3Zs3Izu57DEqGYjN6wlNkGtYf/rec8NWDp8p/I4m3hW4Qgoa5vwy6hZwlIZ9Ma22Unui59mifeZ17ncbrUD78Wk0DX3pYufTzAPbYMiSbU2Zc/fKOGoR7uh0LaAiX1qdTd2qg5GDyWCK9EGlx2/mxIil49QLaGtxiw2iwCGsDxz15TwS1mnvgQLanQ17ZLY8GsJmNEDM70p1nN5Jr89oyoMt44PXMbFNuUhrZ35eszAo3dyIMagZlow2boHx1HeFr8mJaQnDkKTdCiWkCiFZPpKjXmaG1PuZwLWhr6iYWZwFKUAuA4COsRj2N+Z06/60h07EYR6+evXMgZdLp+B8k82QPoRFJLg2iCqqujftPaOYmhjDKNg3L482lyGS6XNRZp+5y3MI9/l+f4J+IR3t59I3XHQprS19ryWVFTAPsxOeJkqkNBZ0StWKLcmICufbKGOIUQEc8TWcyoGG1T9Avk7XUgP37Oji9D55DrxQg0sxMqW6nNGfwZIXYglv9jROJe6OPOACD4UMZieGBComZKFALAjehgSE/6TPTI0OvllF8vV7GskYi26PtpKhFswTdcNDhlIToIg83uSzeP/OTmBokLGnrCDABLEbBs+C+X99bcJE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
